<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery-1.4.2.min.js') ?>"></script>


<script type='text/javascript' src="<?php echo $this->getSkinUrl('js/jquery.hoverIntent.minified.js') ?>"></script>
<script type='text/javascript' src="<?php echo $this->getSkinUrl('js/jquery.dcverticalmegamenu.1.3.js')?>"></script>

<script type="text/javascript">

jQuery.noConflict();

jQuery(document).ready(function($){

	$('#mega-1').dcVerticalMegaMenu({
		rowItems: '3',
		speed: 'fast',
		effect: 'show',
		direction: 'right'
	});


});
</script>

<div class="wrap2">

<div class="demo-container">

<ul id="mega-1" class="mega-menu">
<?php foreach($this->getStoreCategories() as $_category): ?>
<li><a href="<?php echo $this->getCategoryUrl($_category) ?>"><?php echo $this->htmlEscape($_category->getName()) ?></a>

<ul>
<?php
$_catid=$_category->getId();
$category=Mage::getModel('catalog/category')->load($_catid);
$subcategory=$category->getAllChildren(true);
array_shift($subcategory);
foreach($subcategory as $sub)
{
	$sub1=Mage::getModel('catalog/category')->load($sub); ?>
<li><a href="<?php echo $sub1->getUrl(); ?>"><?php echo $sub1->getName(); ?></a></li>
<?php } ?>
</ul></li>
<?php endforeach ?>
</ul>


<div class="clear"></div>
</div>
</div>
