<div>
<h2 class="smh2">All Categories</h2>
<?php $_helper = Mage::helper('catalog/category') ?>
<?php $_categories = $_helper->getStoreCategories() ?>
<?php if (count($_categories) > 0): ?>
	<ul class="sitecatul">
		<?php foreach($_categories as $_category): ?>
			<li style='float:left;width:150px;'>
					<strong class="strongsm"><?php echo $_category->getName() ?></strong>
				<?php $_category = Mage::getModel('catalog/category')->load($_category->getId()) ?>
				<?php $_subcategories = $_category->getChildrenCategories() ?>
				<?php if (count($_subcategories) > 0): ?>
					<ul class='' >
						<?php foreach($_subcategories as $_subcategory): ?>
							<?php $_nextcategory = Mage::getModel('catalog/category')->load($_subcategory->getId()) ?>
                            <?php $_nextsubcategories = $_nextcategory->getChildrenCategories() ?>
							<li>
								<a href="<?php echo $_helper->getCategoryUrl($_subcategory) ?>" title="<?php echo $_subcategory->getName() ?>">
									<?php echo $_subcategory->getName() ?>
								</a>
                                <?php if (count($_nextsubcategories) > 0): ?>
                                <ul>
                                	<?php foreach($_nextsubcategories as $_nextsubcat): ?>
                                    	<li>
                                        	<a href="<?php echo $_helper->getCategoryUrl($_nextsubcat) ?>" title="<?php echo $_subcategory->getName() ?> - <?php echo $_nextsubcat->getName() ?>">
												<?php echo $_nextsubcat->getName() ?>
                                            </a>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                                <?php endif; ?>
							</li>
						<?php endforeach; ?>
					</ul>
				<?php endif; ?>
			</li>
		<?php endforeach; ?>
	</ul>
<?php endif; ?>
</div>
