
<div>
<div class="entry-edit">
<div class="entry-edit-head"   style='height:20px;'>



	<h4><?php echo Mage::helper('hierp')->__('Supplier Information') ?></h4>
	<div class="tools"><?php echo $this->getSupplierEditLink( $this->getSupplier()->getId())?></div>
	<p>
	 </div>
	<div class="fieldset">
	<table cellspacing="0" class="form-list">
	<tr>
		<td class="label"><label><?php echo Mage::helper('hierp')->__('Supplier ID') ?></label></td>
		<td class="value"><strong><?php echo $this->getSupplier()->getId()?></strong></td>
	</tr>
	<tr>
		<td class="label"><label><?php echo Mage::helper('hierp')->__('Supplier Name') ?></label></td>
		<td class="value"><strong><?php echo $this->getSupplier()->getName()?></strong></td>
	</tr>
	<tr>
		<td class="label"><label><?php echo Mage::helper('hierp')->__('Adress') ?></label></td>
		<td class="value"><strong><?php echo $this->getSupplier()->getAddress()?></strong></td>
	</tr>
	<tr>
		<td class="label"><label><?php echo Mage::helper('hierp')->__('Phone') ?></label></td>
		<td class="value"><strong><?php echo $this->getSupplier()->getPhone()?></strong></td>
	</tr>
	<tr>
		<td class="label"><label><?php echo Mage::helper('hierp')->__('Order Date') ?></label></td>
		<td class="value"><strong><?php echo $this->getSupplier()->getId()?></strong></td>
	</tr>
</table></div>
</div>
</div>
<div class="clear"></div>

<div class="box-left">
<div class="entry-edit">
<div class="entry-edit-head">



	<h4><?php echo Mage::helper('hierp')->__('Supplier Information') ?></h4>
	<p>
	 </div>
	<div class="fieldset">
	<table cellspacing="0" class="form-list">
	<tr>
		<td class="label"><label><?php echo Mage::helper('hierp')->__('Supplier ID') ?></label></td>
		<td class="value"><strong><?php echo $this->getSupplier()->getId()?></strong></td>
	</tr>
	<tr>
		<td class="label"><label><?php echo Mage::helper('hierp')->__('Supplier Name') ?></label></td>
		<td class="value"><strong><?php echo $this->getSupplier()->getName()?></strong></td>
	</tr>
	<tr>
		<td class="label"><label><?php echo Mage::helper('hierp')->__('Adress') ?></label></td>
		<td class="value"><strong><?php echo $this->getSupplier()->getAddress()?></strong></td>
	</tr>
	<tr>
		<td class="label"><label><?php echo Mage::helper('hierp')->__('Phone') ?></label></td>
		<td class="value"><strong><?php echo $this->getSupplier()->getPhone()?></strong></td>
	</tr>
	<tr>
		<td class="label"><label><?php echo Mage::helper('hierp')->__('Order Date') ?></label></td>
		<td class="value"><strong><?php echo $this->getSupplier()->getId()?></strong></td>
	</tr>
</table>
</div>
</div>
</div>

